---
layout: cv
title: Danielle's Robinson CV
---
# Danielle Robinson
Physicist, Mathematician, Cambridge professor.

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
<!-- | <a href="https://yourusername.github.io/datascience_portfolio/gh-pages/resume.pdf">Download PDF</a> -->
| <a href="https://github.com/byuidatascience/datascience_portfolio/blob/gh-pages/resume.pdf">Download PDF</a>
</div>


## Currently

Student at Brigham Young University-Idaho, studying Data Science and Communications

### Specialized in
- Data Science
- Communications
- Dance


## Education

`2021-2025`
__Thunder Ridge High School, Ammon, Idaho__

`2023-2025`
__College Of Southern Idaho__
- Associate of Liberal Arts
`September 2025-Now`
__Brigham Young University-Idaho__
- Bachelor of Science in Data Science
- Minor in Communications


## Occupation

`07/2020 – 04/2022`  
__Idaho Falls Wood‑n‑Crafts__, Idaho Falls, ID  
- Customer Service / Cashier  
- Supported customers through the purchasing process and product location.  
- Answered customer calls with efficiency and friendliness.  
- Organized and replenished merchandise for an appealing sales floor.  
- Maintained a clean, professional, and inviting work environment.

`05/2024 – 02/2025`  
__Buckle Youth__, Idaho Falls, ID  
- Customer Service / Cashier  
- Delivered exceptional customer service and memorable shopping experiences.  
- Leveraged strong product knowledge to drive sales and mentor team members.  
- Maintained professionalism and leadership in the manager’s absence.  
- Guided customers in purchase decisions with personalized recommendations.  
- Trained new staff on engagement strategies and sales techniques.




<!-- ### Footer

Last updated: May 2013 -->